### ISSUE TITLE
Angular 2 support 

### ISSUE THREAD

**Issue by anishmenon** [mw-ferretti/angular-resource-tastypie#10]
angular-resource-tastypie is a wonderful source .  Will this supports Angular 2 ? . 

Google has clearly mentioned that they'll not only maintain but work of fixes/improvements on 1.x branch. 1.5.x branch is an example of this where they've introduced components.

i'm jus a starter in angular but not in PyDj . Its just a request to implement Angular 2 compatibility 

https://github.com/Paldom/angular2-rest

**Comment by mw-ferretti** [comment]
Thank you friend. 
I will study and implement. 
Thank you.

**Comment by mw-ferretti** [comment]
done!
https://github.com/mw-ferretti/ts-resource-tastypie
