### ISSUE TITLE
setauth params later after authenticatino

### ISSUE THREAD

**Issue by RajatGoyal** [mw-ferretti/angular-resource-tastypie#2]
What if I want to set user authentication parameters after the app has initialized and user is authenticated using a controller.

$tastypieProvider.setAuth('username','api_key');

seems to work only in the app.config. Otherwise I get

Error: [$injector:unpr] Unknown provider: $tastypieProviderProvider <- $tastypieProvider <- SignInCtrl
http://errors.angularjs.org/1.3.6/$injector/unpr?p0=%24tastypieProviderProvider%20%3C-%20%24tastypieProvider%20%3C-%20SignInCtrl

Even when $tastypieProvider is injected properly.

**Comment by mw-ferretti** [comment]
Hi.
Use '$tastypie'.

Ex:
.controller('MyCtrl', ['$scope', '$tastypieResource', '$tastypie', function($scope, $tastypieResource, $tastypie){
    $tastypie.setAuth('username', 'api_key');
}]);

In the next days, I will be releasing 1.0 version. It will have minor changes and documentation improvements. Thank you for using.

**Comment by RajatGoyal** [comment]
Hey thanks, I set the auth headers in the controller manually.
Btw, thanks for a such a great job!
It needed a trailing slash fix, https://github.com/guilhermegm/angular-resource-tastypie/commit/80d22934214cb6cda04c48611699848f7fed5b02  fork seems to fix it, please include it in 1.0

**Comment by mw-ferretti** [comment]
Ok .. will be included.
thanks.
