### ISSUE TITLE
new feature idea: auto-generation of angular services and html forms based on tastypie-swagger or any json schema 

### ISSUE THREAD

**Issue by flamby** [mw-ferretti/angular-resource-tastypie#7]
Hi,

First, kudos for this lib, it's a huge time saver!

I wonder if - w/ or w/o a json schema - we could enhance this lib to "auto-discover" tastypie models, and thus, auto-generate them as angular.js services.

Since tastypie-swagger is basically guessing the schema for documentation purposes, one might hijack that to auto-generate angular services based on your lib, avoiding to write boilerplate code at the js layer (basically declaration of angular services, and most of the CRUD forms' html/angular directives code).

What do you think?

**Comment by mw-ferretti** [comment]
Hi.
Thank you.
I find this very good idea. I had already thought of that, but when I met the "angular material" that contains many ready directives, left it aside. Today it is so easy to use frameworks (bootstrap, angular material, Younic), that my form would hinder rather than help. lol. And also for quick entries, there is a "django admin" that works very well with an administrative support.

**Comment by flamby** [comment]
Hi Marco,

In fact, I think it's complementary to django admin, which is suitable for backend admin (not using tastypie/drf at all), whereas the kind of view that you did using material, is the one that people tend to give to the end user, with more restriction applied. Right now, when one wants to consume a rest api from a SPA app made w/ angular, he has to write lots of boilerplate code. This is where a generic version of your lib+angular material sample app could give a out-of-the-box admin UI for the end user, as opposed to django admin which is too dangerous to give to the end-user. It has the advantage to follow the eat-your-own-dog-food approach regarding API (kind of virtuous cycle).

If i've time in the coming days, i'll look into that, because it's a repeating pattern I'm having and probably not the only one ;-)

**Comment by mw-ferretti** [comment]
So the context of my lib is generic for developers, not for end User. The programmer can consume web services and connect to your frontend any. There are endless possibilities for frontend. My lib is only the model of MVC, has no directives (view). For example, you said that this repeating patterns, what framework you're using for the layout? This layout is your project, the lib have to keep generic for any project (layout). I think we have to keep it that simple. I like your idea, but for a new project on top just this context, creating an admin for tastypie using my lib. What do you think?

**Comment by flamby** [comment]
yeah, you're absolutely right, better to do that outside of the scope of this lib.
and it's really a material design admin UI for tastypie that i've in mind, probably using built-in schema of tastypie

**Comment by mw-ferretti** [comment]
Ok, thanks for the use of the lib. I'm having the same problem as you, lack of time to start new projects. We can start this project together soon, I liked the idea.
See you.
