### ISSUE TITLE
multiple endpoint

### ISSUE THREAD

**Issue by flamby** [mw-ferretti/angular-resource-tastypie#9]
Hi,
I can't find a proper way to handle within my app different endpoints.
is it possible w/o hacking the tastypieprovider?
Usually, similar orm have a such syntax:
config
      .registerEndpoint('auth', 'https://auth.myapi.org/')
      .registerEndpoint('admin', 'https://admin.myapi.org/')
      .setDefaultEndpoint('auth');

TIA

**Comment by mw-ferretti** [comment]
Hi flamby.
Great question. I also came across this. 
I found the solution in the "SOA" study. The solution is in the backend. In "SOA" us have "service bus" called "middleware". In fact we can use the "listendpoint" django tastypie for this. You can create a simple "endpoint" and encapsulate the call to another provider (url).  In this way, you will focus all your services in one web address that lists the endpoints. Implement a system of "multi provider" was quite tempting. But when I studied the concept of "middleware", I did not see the need to implement the "MultiProvider.". What do you think?

**Comment by flamby** [comment]
Hi Marco,
thanks for your answer. unfortunately, i have in my present use-case no access to the APIs :-(
i digged in singleton vs transient factory/services of angular to address my need (i.e. several autonomous instances of tastypieprovider w/ different endpoints), but did not find a proper way to do it. do you think it's achievable w/ a such hack?

**Comment by mw-ferretti** [comment]
Ok. I'll implement. I liked the idea. It may be useful for various frontend developers. I'm about to get a new version with a new feature, so I climb the "multprovider" together. I intend to climb this weekend or before.

**Comment by flamby** [comment]
Hi Marco,
Cool. Thanks a lot.

**Comment by mw-ferretti** [comment]
Hi flamby. Sorry about the delay, I was busy with a private project. I have concluded the "multi provider". You can update to the latest version.

Usage:
https://github.com/mw-ferretti/angular-resource-tastypie#multi-provider-sample

Thanks for the idea.

**Comment by flamby** [comment]
Hi Marco,

No problem at all. It's very nice from you. I'll test it this week.

Many thanks.

BTW i'm, like many, investigating time on angular 2 (lots of benefits), so +1 for #10 ;-)

**Comment by mw-ferretti** [comment]
Ok .. I'm studying angular 2 (ECMAScript 6) as well. See you.
